<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="6" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-26T15:08:36 IST" name="BillHub Test Automation Test Suite" finished-at="2024-02-26T15:09:43 IST" duration-ms="66825">
    <groups>
    </groups>
    <test started-at="2024-02-26T15:08:36 IST" name="BillHub App Test Cases" finished-at="2024-02-26T15:09:43 IST" duration-ms="66825">
      <class name="com.billhub.qa.testcases.ReasonPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.billhub.qa.testcases.ReasonPageTest@3c41ed1d]" started-at="2024-02-26T15:08:36 IST" name="setup" finished-at="2024-02-26T15:09:09 IST" duration-ms="33173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="addNewReasonWithValidDataTest()[pri:1, instance:com.billhub.qa.testcases.ReasonPageTest@3c41ed1d]" started-at="2024-02-26T15:09:09 IST" name="addNewReasonWithValidDataTest" finished-at="2024-02-26T15:09:11 IST" duration-ms="1234" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewReasonWithValidDataTest -->
        <test-method signature="addNewReasonWithInvalidDataTest()[pri:2, instance:com.billhub.qa.testcases.ReasonPageTest@3c41ed1d]" started-at="2024-02-26T15:09:11 IST" name="addNewReasonWithInvalidDataTest" finished-at="2024-02-26T15:09:24 IST" duration-ms="13802" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewReasonWithInvalidDataTest -->
        <test-method signature="addNewReasonWithoutDataTest()[pri:3, instance:com.billhub.qa.testcases.ReasonPageTest@3c41ed1d]" started-at="2024-02-26T15:09:24 IST" name="addNewReasonWithoutDataTest" finished-at="2024-02-26T15:09:35 IST" duration-ms="10419" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewReasonWithoutDataTest -->
        <test-method signature="addNewReasonWithDuplicateDataTest()[pri:4, instance:com.billhub.qa.testcases.ReasonPageTest@3c41ed1d]" started-at="2024-02-26T15:09:35 IST" name="addNewReasonWithDuplicateDataTest" finished-at="2024-02-26T15:09:36 IST" duration-ms="1263" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Duplicate data was added. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Duplicate data was added. expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at com.billhub.qa.testcases.ReasonPageTest.addNewReasonWithDuplicateDataTest(ReasonPageTest.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addNewReasonWithDuplicateDataTest -->
        <test-method signature="updateReasonTest()[pri:5, instance:com.billhub.qa.testcases.ReasonPageTest@3c41ed1d]" started-at="2024-02-26T15:09:36 IST" name="updateReasonTest" finished-at="2024-02-26T15:09:41 IST" duration-ms="5180" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateReasonTest -->
        <test-method signature="searchByReasonNameTest()[pri:6, instance:com.billhub.qa.testcases.ReasonPageTest@3c41ed1d]" started-at="2024-02-26T15:09:41 IST" name="searchByReasonNameTest" finished-at="2024-02-26T15:09:43 IST" duration-ms="1332" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchByReasonNameTest -->
        <test-method signature="searchByReasonCodeTest()[pri:7, instance:com.billhub.qa.testcases.ReasonPageTest@3c41ed1d]" started-at="2024-02-26T15:09:43 IST" name="searchByReasonCodeTest" finished-at="2024-02-26T15:09:43 IST" duration-ms="270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchByReasonCodeTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.billhub.qa.testcases.ReasonPageTest@3c41ed1d]" started-at="2024-02-26T15:09:43 IST" name="tearDown" finished-at="2024-02-26T15:09:43 IST" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.billhub.qa.testcases.ReasonPageTest -->
    </test> <!-- BillHub App Test Cases -->
  </suite> <!-- BillHub Test Automation Test Suite -->
</testng-results>
